### ISSUE TITLE
如何使用

### ISSUE THREAD

**Issue by kongzhecn** [zeze0556/get_huggingface_file_url#1]
非常感谢作者分享工具，想问下这个脚本如何插入chrome浏览器，可以提供更为详细一点的安装教程吗？

**Comment by zeze0556** [comment]
tampermonkey 插件-》管理面板-》实用工具
从URL安装：https://raw.githubusercontent.com/zeze0556/get_huggingface_file_url/main/src/huggingface_copy.js

**Comment by kongzhecn** [comment]
成功了，非常感谢
